import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'ar' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string | { ar: string; en: string }) => string;
  tx: (ar: string, en: string) => string;
  isAr: boolean;
}

const translationsFull = {
  ar: {
    home: "الرئيسية",
    shop: "المتجر",
    myAccount: "حسابي",
    myOrders: "طلباتي",
    adminPanel: "لوحة التحكم",
    installApp: "تثبيت التطبيق",
    connectWithUs: "تواصل معنا",
    categories: "التصنيفات",
    allProducts: "جميع المنتجات",
    help: "المساعدة",
    terms: "الشروط والأحكام",
    faq: "الأسئلة الشائعة",
    contactUs: "تواصل معنا",
    callUs: "اتصل بنا",
    email: "البريد الإلكتروني",
    whatsapp: "واتساب",
    allRightsReserved: "جميع الحقوق محفوظة",
    madeWithLove: "RF Perfume — Abayas by HMBL",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    cart: "السلة",
    newCollection: "تشكيلة موسم ٢٠٢٦",
    heroTitle: "أناقة تُعبّر عن هويتك",
    heroDesc: "تشكيلات عبايات راقية مصممة بعناية فائقة من قلب الرياض. جودة استثنائية وتفاصيل تعكس أناقتك.",
    discoverCollection: "اكتشف التشكيلة",
    featuredItem: "منتج مميز",
    exclusivePicks: "المختارات الحصرية",
    viewAllProducts: "عرض جميع المنتجات",
    ourMission: "مهمتنا",
    qualityIsIdentity: "الجودة هي هويتنا",
    brandStoryDesc: "في RF Perfume، نؤمن أن العباية ليست مجرد لباس — بل هي تعبير عن الهوية والرقي. نصمم كل تشكيلة بعشق وعناية لتعكس جمالك وأصالتك.",
    happyCustomers: "عميل سعيد",
    masterCraftsmanship: "تصميم متقن",
    exceptionalQuality: "جودة استثنائية",
    exceptionalQualityDesc: "تصاميم مختارة بعناية لكل مناسبة",
    fastShipping: "شحن سريع",
    fastShippingDesc: "توصيل لباب منزلك في أسرع وقت",
    goldenGuarantee: "ضمان الجودة",
    goldenGuaranteeDesc: "تسوق بكل ثقة مع سياسة استرجاع مرنة",
    stayExclusive: "كن أول من يعلم",
    newsletterDesc: "كن أول من يعلم عن الإصدارات الجديدة والعروض الحصرية. انضم إلى قائمتنا البريدية.",
    emailPlaceholder: "بريدك الإلكتروني",
    subscribe: "اشتراك",
    fullCollection: "المجموعة كاملة",
    searchPlaceholder: "ابحثي عن عبايتك...",
    noResults: "لا توجد منتجات تطابق بحثك حالياً.",
    productNotFound: "المنتج غير موجود",
    viewDetails: "عرض التفاصيل",
    currency: "ر.س",
    startingFrom: "ابتداءً من",
    addedToCart: "تمت الإضافة للسلة",
    addedToCartDesc: "أضيف إلى سلة مشترياتك.",
    optionsLabel: "الخيار (الحجم / اللون)",
    colorLabel: "اختر اللون",
    sizeLabel: "اختر المقاس",
    lengthLabel: "اختر الطول",
    sizeGuide: "دليل المقاسات",
    notesLabel: "ملاحظات",
    notesItemPlaceholder: "أضيفي أي ملاحظة على طلبك (تعديل الطول، تطريز، تغليف هدية...)",
    quantityLabel: "الكمية",
    addToCart: "إضافة إلى السلة",
    originalProduct: "تصميم أصيل وحصري",
    luxuryPackaging: "تغليف فاخر",
    secureShipping: "شحن سريع وآمن",
    featured: "مميز",
    emptyCart: "سلة المشتريات فارغة",
    emptyCartDesc: "لم تقم بإضافة أي منتجات للسلة بعد.",
    shoppingBag: "سلة التسوق",
    removeItem: "إزالة المنتج",
    bagSummary: "ملخص السلة",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة (١٥٪)",
    total: "الإجمالي",
    checkout: "إتمام عملية الشراء",
    freeShippingPromo: "شحن مجاني على جميع الطلبات لفترة محدودة",
    orderCheckout: "إتمام الطلب",
    deliveryMethod: "طريقة الاستلام",
    deliveryStorage: "توصيل للمنزل",
    pickupFromBranch: "استلام من الفرع",
    selectBranch: "اختر الفرع",
    paymentMethod: "طريقة الدفع",
    cod: "الدفع عند الاستلام",
    bankTransfer: "تحويل بنكي",
    orderSummary: "ملخص الطلب",
    placeOrder: "تأكيد الطلب",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    fullName: "الاسم الكامل",
    phone: "رقم الجوال",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    technicalSupport: "هل تواجه مشكلة؟ تواصل مع الدعم الفني",
    browseProducts: "تصفح المنتجات",

    // Common UI
    loading: "جارٍ التحميل...",
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    delete: "حذف",
    edit: "تعديل",
    update: "تحديث",
    add: "إضافة",
    close: "إغلاق",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    search: "بحث",
    filter: "تصفية",
    sortBy: "ترتيب حسب",
    yes: "نعم",
    no: "لا",
    ok: "حسناً",
    error: "خطأ",
    success: "تم بنجاح",
    warning: "تنبيه",
    info: "معلومة",
    required: "مطلوب",
    optional: "اختياري",
    submit: "إرسال",
    sending: "جارٍ الإرسال...",
    saving: "جارٍ الحفظ...",
    processing: "جارٍ المعالجة...",
    tryAgain: "حاول مرة أخرى",
    retry: "إعادة المحاولة",
    viewMore: "عرض المزيد",
    viewLess: "عرض أقل",
    seeAll: "عرض الكل",
    showMore: "المزيد",
    showLess: "أقل",

    // Account / Profile
    profile: "الملف الشخصي",
    accountSettings: "إعدادات الحساب",
    personalInfo: "المعلومات الشخصية",
    addresses: "العناوين",
    paymentMethods: "طرق الدفع",
    wishlist: "المفضلة",
    orders: "الطلبات",
    invoices: "الفواتير",
    wallet: "المحفظة",
    walletBalance: "رصيد المحفظة",
    cashback: "كاش باك",
    points: "النقاط",
    loyaltyPoints: "نقاط الولاء",
    welcomeBack: "مرحباً بعودتك",

    // Orders
    orderNumber: "رقم الطلب",
    orderDate: "تاريخ الطلب",
    orderStatus: "حالة الطلب",
    orderTotal: "إجمالي الطلب",
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    preparing: "قيد التحضير",
    shipped: "تم الشحن",
    outForDelivery: "في الطريق إليك",
    delivered: "تم التسليم",
    cancelled: "ملغي",
    refunded: "مسترد",
    noOrders: "لا توجد طلبات حالياً",
    trackOrder: "تتبع الطلب",
    reorder: "إعادة الطلب",

    // Cart / Checkout
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    discount: "خصم",
    discountCode: "كود الخصم",
    applyCode: "تطبيق",
    invalidCode: "كود الخصم غير صحيح أو منتهي",
    codeApplied: "تم تطبيق الكود",
    shipping: "الشحن",
    free: "مجاني",
    continueShopping: "متابعة التسوق",
    proceedToCheckout: "إتمام الشراء",
    deliveryAddress: "عنوان التوصيل",
    addNewAddress: "إضافة عنوان جديد",
    chooseAddress: "اختر العنوان",
    notes: "ملاحظات",
    notesPlaceholder: "أي ملاحظات إضافية للطلب...",

    // Product
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    onlyXLeft: "تبقى {n} فقط",
    productCode: "كود المنتج",
    description: "الوصف",
    specifications: "المواصفات",
    reviews: "التقييمات",
    relatedProducts: "منتجات مشابهة",
    addToWishlist: "أضف للمفضلة",
    removedFromWishlist: "تمت إزالته من المفضلة",
    addedToWishlist: "تمت إضافته للمفضلة ❤️",
    share: "مشاركة",
    rating: "التقييم",
    writeReview: "اكتب تقييماً",
    reviewSubmitted: "تم إرسال التقييم بنجاح",

    // Home / Marketing
    limitedTime: "وقت محدود",
    todaysDeals: "عروض اليوم",
    endsIn: "ينتهي خلال",
    days: "أيام",
    hours: "ساعات",
    minutes: "دقائق",
    seconds: "ثوانٍ",
    bestSellers: "الأكثر مبيعاً",
    newArrivals: "وصل حديثاً",
    sale: "تخفيضات",
    shopNow: "تسوق الآن",
    discoverMore: "اكتشف المزيد",
    seller: "بائع مستقل",
    added: "تمت الإضافة",

    // Notifications
    notifications: "الإشعارات",
    markAllRead: "قراءة الكل",
    noNotifications: "لا توجد إشعارات",
    justNow: "الآن",
    minutesAgo: "منذ {n} دقيقة",
    hoursAgo: "منذ {n} ساعة",
    daysAgo: "منذ {n} يوم",

    // Layout / nav extras
    payment: "الدفع",
    welcome: "مرحباً بك",
    items: "منتجات",
    navigation: "القائمة الرئيسية",
    settings: "الإعدادات",
    more: "المزيد",
    new: "جديد",
    call: "اتصل",
    availablePayments: "طرق الدفع المتاحة",
    commercialReg: "سجل تجاري",
    taxNumber: "الرقم الضريبي",
    footerTagline: "عبايات راقية من قلب الرياض · RF Perfume — Abayas by HMBL",
    enterCoupon: "أدخل الكود",
    apply: "تطبيق",
    couponAdded: "تمت إضافة كود الخصم بنجاح",
    couponFailed: "فشل تطبيق الكود",
    vendorDashboard: "لوحة البائع",

    // Home extras
    freeShippingTitle: "شحن مجاني",
    freeShippingSub: "فوق ١٠٠ ر.س",
    original100: "أصلي ١٠٠٪",
    qualityGuaranteed: "ضمان الجودة",
    freeReturns: "إرجاع مجاني",
    within14Days: "خلال ١٤ يوم",
    support247: "دعم ٢٤/٧",
    dedicatedTeam: "فريق متخصص",
    customerFavorites: "اختيارات العملاء",
    viewAll: "عرض الكل",
    flexiblePayment: "طرق الدفع المرنة",
    buyNowPayLater: "اشتري الآن وادفع لاحقاً",
    buyNow: "اشتري الآن",
    payLater: "وادفع لاحقاً",
    luxuryFragrances: "عبايات فاخرة",
    customerSatisfaction: "رضا العملاء",
    deliveryDays: "أيام توصيل",
    discoverFullCollection: "اكتشف التشكيلة الكاملة",
    endsInShort: "تنتهي خلال",

    // Auth modal
    createAccount: "إنشاء الحساب",
    newAccount: "حساب جديد",
    continueWithApple: "المتابعة مع Apple",
    continueWithGoogle: "المتابعة مع Google",
    orWithPhone: "أو بالهاتف",
    phoneNumber: "رقم الهاتف",
    fullNamePlaceholder: "فلان الفلاني",
    or: "أو",
    noAccountYet: "ليس لديك حساب؟",
    createNewAccount: "أنشئ حساب جديد",
    haveAccount: "لديك حساب؟",
    signInShort: "سجّل دخولك",
    passwordRecovery: "استعادة كلمة المرور",
    verifyCode: "تحقق من الكود",
    resendCode: "إعادة إرسال الكود",
    verifyAnotherWay: "التحقق بطريقة أخرى",
    verifyAndContinue: "تحقق وتابع",
    saveNewPassword: "حفظ كلمة المرور الجديدة",
    previousOrderNumber: "رقم طلب سابق",
    fullNameAsAccount: "الاسم الكامل (كما في الحساب)",
    enterPhoneFirst: "أدخل رقم الجوال أولاً",
  },
  en: {
    home: "Home",
    shop: "Shop",
    myAccount: "My Account",
    myOrders: "My Orders",
    adminPanel: "Admin Panel",
    installApp: "Install App",
    connectWithUs: "Connect with us",
    categories: "Categories",
    allProducts: "All Products",
    help: "Help",
    terms: "Terms & Conditions",
    faq: "FAQ",
    contactUs: "Contact Us",
    callUs: "Call Us",
    email: "Email",
    whatsapp: "WhatsApp",
    allRightsReserved: "All rights reserved",
    madeWithLove: "RF Perfume",
    signIn: "Sign In",
    signOut: "Sign Out",
    cart: "Cart",
    newCollection: "New Collection 2026",
    heroTitle: "Elegance That Expresses Your Identity",
    heroDesc: "Curated collections of refined abayas crafted with exceptional care from the heart of Riyadh. Exceptional quality and details reflecting your elegance.",
    discoverCollection: "Discover Collection",
    featuredItem: "Featured Product",
    exclusivePicks: "Exclusive Picks",
    viewAllProducts: "View All Products",
    ourMission: "Our Mission",
    qualityIsIdentity: "Quality is Our Identity",
    brandStoryDesc: "At RF Perfume, we believe an abaya is more than a garment — it's an expression of identity and refinement. We design every collection with passion and care to reflect your beauty and authenticity.",
    happyCustomers: "Happy Customers",
    masterCraftsmanship: "Refined Craftsmanship",
    exceptionalQuality: "Exceptional Quality",
    exceptionalQualityDesc: "Carefully curated designs for every occasion",
    fastShipping: "Fast Shipping",
    fastShippingDesc: "Delivery to your doorstep in no time",
    goldenGuarantee: "Quality Guarantee",
    goldenGuaranteeDesc: "Shop with confidence with a flexible return policy",
    stayExclusive: "Stay Informed",
    newsletterDesc: "Be the first to know about new arrivals and exclusive offers. Join our mailing list.",
    emailPlaceholder: "Your Email Address",
    subscribe: "Subscribe",
    fullCollection: "Full Collection",
    searchPlaceholder: "Search for your abaya...",
    noResults: "No products match your search currently.",
    productNotFound: "Product not found",
    viewDetails: "View Details",
    currency: "SAR",
    startingFrom: "Starting from",
    addedToCart: "Added to Cart",
    addedToCartDesc: "has been added to your shopping cart.",
    optionsLabel: "Option (Size / Color)",
    colorLabel: "Select Color",
    sizeLabel: "Select Size",
    lengthLabel: "Select Length",
    sizeGuide: "Size Guide",
    notesLabel: "Notes",
    notesItemPlaceholder: "Add any note to your order (length adjustment, embroidery, gift wrap...)",
    quantityLabel: "Quantity",
    addToCart: "Add to Cart",
    originalProduct: "Authentic & Exclusive Design",
    luxuryPackaging: "Premium Packaging",
    secureShipping: "Fast & Secure Shipping",
    featured: "Featured",
    emptyCart: "Your shopping cart is empty",
    emptyCartDesc: "You haven't added any products to your cart yet.",
    shoppingBag: "Shopping Cart",
    removeItem: "Remove Item",
    bagSummary: "Cart Summary",
    subtotal: "Subtotal",
    tax: "Tax (15%)",
    total: "Total",
    checkout: "Proceed to Checkout",
    freeShippingPromo: "Free shipping on all orders for a limited time",
    orderCheckout: "Order Checkout",
    deliveryMethod: "Collection Method",
    deliveryStorage: "Home Delivery",
    pickupFromBranch: "Pickup from Branch",
    selectBranch: "Select Branch",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery",
    bankTransfer: "Bank Transfer",
    orderSummary: "Order Summary",
    placeOrder: "Confirm Order",
    username: "Username",
    password: "Password",
    login: "Login",
    register: "Register",
    fullName: "Full Name",
    phone: "Phone Number",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    technicalSupport: "Facing an issue? Contact technical support",
    browseProducts: "Browse Products",

    // Common UI
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    update: "Update",
    add: "Add",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    search: "Search",
    filter: "Filter",
    sortBy: "Sort by",
    yes: "Yes",
    no: "No",
    ok: "OK",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    required: "Required",
    optional: "Optional",
    submit: "Submit",
    sending: "Sending...",
    saving: "Saving...",
    processing: "Processing...",
    tryAgain: "Try again",
    retry: "Retry",
    viewMore: "View more",
    viewLess: "View less",
    seeAll: "See all",
    showMore: "Show more",
    showLess: "Show less",

    // Account / Profile
    profile: "Profile",
    accountSettings: "Account Settings",
    personalInfo: "Personal Information",
    addresses: "Addresses",
    paymentMethods: "Payment Methods",
    wishlist: "Wishlist",
    orders: "Orders",
    invoices: "Invoices",
    wallet: "Wallet",
    walletBalance: "Wallet Balance",
    cashback: "Cashback",
    points: "Points",
    loyaltyPoints: "Loyalty Points",
    welcomeBack: "Welcome back",

    // Orders
    orderNumber: "Order #",
    orderDate: "Order Date",
    orderStatus: "Order Status",
    orderTotal: "Order Total",
    pending: "Pending",
    confirmed: "Confirmed",
    preparing: "Preparing",
    shipped: "Shipped",
    outForDelivery: "Out for Delivery",
    delivered: "Delivered",
    cancelled: "Cancelled",
    refunded: "Refunded",
    noOrders: "No orders yet",
    trackOrder: "Track Order",
    reorder: "Reorder",

    // Cart / Checkout
    quantity: "Quantity",
    unitPrice: "Unit Price",
    discount: "Discount",
    discountCode: "Discount Code",
    applyCode: "Apply",
    invalidCode: "Invalid or expired discount code",
    codeApplied: "Code applied",
    shipping: "Shipping",
    free: "Free",
    continueShopping: "Continue Shopping",
    proceedToCheckout: "Proceed to Checkout",
    deliveryAddress: "Delivery Address",
    addNewAddress: "Add new address",
    chooseAddress: "Choose address",
    notes: "Notes",
    notesPlaceholder: "Any extra notes for the order...",

    // Product
    inStock: "In stock",
    outOfStock: "Out of stock",
    onlyXLeft: "Only {n} left",
    productCode: "Product Code",
    description: "Description",
    specifications: "Specifications",
    reviews: "Reviews",
    relatedProducts: "Related Products",
    addToWishlist: "Add to Wishlist",
    removedFromWishlist: "Removed from wishlist",
    addedToWishlist: "Added to wishlist ❤️",
    share: "Share",
    rating: "Rating",
    writeReview: "Write a review",
    reviewSubmitted: "Review submitted successfully",

    // Home / Marketing
    limitedTime: "Limited Time",
    todaysDeals: "Today's Deals",
    endsIn: "Ends in",
    days: "days",
    hours: "hours",
    minutes: "minutes",
    seconds: "seconds",
    bestSellers: "Best Sellers",
    newArrivals: "New Arrivals",
    sale: "Sale",
    shopNow: "Shop Now",
    discoverMore: "Discover More",
    seller: "Independent Seller",
    added: "Added!",

    // Notifications
    notifications: "Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No notifications",
    justNow: "Just now",
    minutesAgo: "{n} min ago",
    hoursAgo: "{n} h ago",
    daysAgo: "{n} d ago",

    // Layout / nav extras
    payment: "Payment",
    welcome: "Welcome",
    items: "items",
    navigation: "Navigation",
    settings: "Settings",
    more: "More",
    new: "NEW",
    call: "Call",
    availablePayments: "Available Payment Methods",
    commercialReg: "Commercial Registration",
    taxNumber: "Tax Number",
    footerTagline: "The Spirit of Japan from the Heart of Riyadh · リヤドの中心部に日本の精神をお届けします。",
    enterCoupon: "Enter code",
    apply: "Apply",
    couponAdded: "Discount code applied",
    couponFailed: "Failed to apply code",
    vendorDashboard: "Vendor Dashboard",

    // Home extras
    freeShippingTitle: "Free Shipping",
    freeShippingSub: "Above 100 SAR",
    original100: "100% Authentic",
    qualityGuaranteed: "Quality guaranteed",
    freeReturns: "Free Returns",
    within14Days: "Within 14 days",
    support247: "24/7 Support",
    dedicatedTeam: "Dedicated team",
    customerFavorites: "Customer Favorites",
    viewAll: "View All",
    flexiblePayment: "Flexible Payment",
    buyNowPayLater: "Buy Now Pay Later",
    buyNow: "Buy Now",
    payLater: "Pay Later",
    luxuryFragrances: "Luxury Abayas",
    customerSatisfaction: "Customer Satisfaction",
    deliveryDays: "Days Delivery",
    discoverFullCollection: "Discover the full collection",
    endsInShort: "Ends in",

    // Auth modal
    createAccount: "Create Account",
    newAccount: "New Account",
    continueWithApple: "Continue with Apple",
    continueWithGoogle: "Continue with Google",
    orWithPhone: "Or with phone",
    phoneNumber: "Phone Number",
    fullNamePlaceholder: "John Doe",
    or: "OR",
    noAccountYet: "Don't have an account?",
    createNewAccount: "Create a new account",
    haveAccount: "Already have an account?",
    signInShort: "Sign in",
    passwordRecovery: "Password Recovery",
    verifyCode: "Verify Code",
    resendCode: "Resend Code",
    verifyAnotherWay: "Verify another way",
    verifyAndContinue: "Verify & Continue",
    saveNewPassword: "Save New Password",
    previousOrderNumber: "Previous order number",
    fullNameAsAccount: "Full Name (as on account)",
    enterPhoneFirst: "Enter your phone number first",
  }
};

const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'ar',
      isAr: true,
      setLanguage: (lang) => {
        set({ language: lang, isAr: lang === 'ar' });
        if (typeof document !== 'undefined') {
          document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
          document.documentElement.lang = lang;
        }
      },
      t: (key) => {
        const { language } = get();
        if (typeof key === 'object' && key !== null) {
          return key[language] || key.ar || '';
        }
        const translations = translationsFull[language] as Record<string, string>;
        return translations[key] || key;
      },
      tx: (ar, en) => {
        const { language } = get();
        return language === 'ar' ? ar : en;
      },
    }),
    {
      name: 'rf perfume-language',
      partialize: (state) => ({ language: state.language, isAr: state.isAr }),
    }
  )
);

export const useLanguage = useLanguageStore;
